name: BookLeaf CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version (adjust if needed)
          cache: "npm" # Cache npm dependencies
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
